{config, ...}: {
  age.rekey = {
    # This file is generated by openssh on the host
    hostPubkey = "/etc/ssh/ssh_host_ed25519_key.pub";

    masterIdentities = [
      ./id_ed25519_sk_rk.pub
    ];

    storageMode = "local";
    localStorageDir = ./. + "/secrets/rekeyed/${config.networking.hostName}";
  };

  age.secrets = {
    user-password.rekeyFile = "";
  };
}
