{config, ...}: {
  age.rekey = {
    # This file is generated by openssh on the host
    hostPubkey = "/etc/ssh/ssh_host_ed25519_key.pub";

    masterIdentities = [
      # TODO fill this when i get my yubikeys
    ];

    storageMode = "local";
    localStorageDir = ./. + "/secrets/rekeyed/${config.networking.hostName}";
  };
}
